'use client';
import {useEffect,useRef,useState} from 'react';
import {Menu,X,ArrowUpRight} from 'lucide-react';
import s from './cinematic.module.css';
const links=[['Home','/','home'],['Product','/marketplace','marketplace'],['Evidence','/evidence','evidence'],['Developers','/developers','developers']];
export function CinematicHeader({active}:{active?:string}){
 const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const menu=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}if(e.key==='Tab'){const items=[toggle.current,...Array.from(menu.current?.querySelectorAll<HTMLAnchorElement>('a')??[])].filter(Boolean) as HTMLElement[];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};const resize=()=>{if(innerWidth>760)setOpen(false);};document.addEventListener('keydown',key);window.addEventListener('resize',resize);return()=>{document.removeEventListener('keydown',key);window.removeEventListener('resize',resize);};},[open]);
 return <header className={s.header}><a className={s.logo} href="/" aria-label="Obolos home"><img src="/landing/assets/logo.webp" width="34" height="34" alt=""/></a><nav className={s.nav} aria-label="Main navigation">{links.map(([label,href,id])=><a href={href} key={id} aria-current={active===id?'page':undefined}>{label}</a>)}</nav><a className={s.account} href="/app">Workspace <ArrowUpRight size={15}/></a><button ref={toggle} className={s.toggle} aria-expanded={open} aria-label={open?'Close navigation':'Open navigation'} aria-controls="product-menu" onClick={()=>setOpen(!open)}>{open?<X size={21}/>:<Menu size={21}/>}</button>{open&&<><button className={s.backdrop} aria-label="Close navigation overlay" tabIndex={-1} onClick={()=>{setOpen(false);toggle.current?.focus();}}/><div className={s.menu} id="product-menu" ref={menu}><nav aria-label="Mobile navigation">{links.map(([label,href,id])=><a key={id} href={href} aria-current={active===id?'page':undefined}>{label}</a>)}<a href="/app">Open workspace ↗</a></nav></div></>}</header>;
}
export function CinematicBackground(){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{if(motion.matches)ref.current?.pause();else void ref.current?.play().catch(()=>{});};sync();motion.addEventListener('change',sync);return()=>motion.removeEventListener('change',sync);},[]);return <div className={s.background} aria-hidden="true"><video ref={ref} autoPlay muted loop playsInline preload="metadata" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260809_012548_ef22562c-c0ae-4816-ad9d-f8922af4e6a7.mp4"/></div>;}
