'use client';
import {useState, type FormEvent} from 'react';
import {api,errorMessage} from './api';
import s from './platform.module.css';
import e from './economy-workspace.module.css';
type Recovery={orderId:string;canDispute:boolean;canRefund:boolean;disputes:{reason:string}[];refunds:{transaction_hash:string;amount_atomic:string}[];reviews:{reviewer:string;verdict:string}[];refundPolicy:string};
export function EconomyRecovery(){
 const [orderId,setOrderId]=useState(''),[record,setRecord]=useState<Recovery|null>(null),[reason,setReason]=useState(''),[hash,setHash]=useState(''),[logIndex,setLogIndex]=useState(''),[amount,setAmount]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(event:FormEvent){event.preventDefault();setBusy('read');setError('');setMessage('');setRecord(null);try{setRecord(await api<Recovery>(`/api/economy/orders/${orderId.toLowerCase()}/recovery`));}catch(caught){setError(errorMessage(caught));}finally{setBusy('');}}
 async function submit(event:FormEvent,action:'dispute'|'refund'){event.preventDefault();if(!record)return;setBusy(action);setError('');setMessage('');try{await api(`/api/economy/orders/${record.orderId}/recovery`,{method:'POST',body:JSON.stringify(action==='dispute'?{action,reason}:{action,transactionHash:hash.toLowerCase(),logIndex:Number(logIndex),amountAtomic:amount})});setRecord(await api<Recovery>(`/api/economy/orders/${record.orderId}/recovery`));setMessage(action==='dispute'?'Dispute recorded. This does not reverse the settlement.':'Finalized refund transfer recorded.');}catch(caught){setError(errorMessage(caught));}finally{setBusy('');}}
 return <details className={e.details}><summary>Disputes and completed refunds</summary><div className={e.actionPanel}>
 <p>Buyers can record a dispute. Sellers can attach proof of a refund already sent on Arc testnet. Refunds are voluntary; the original payment is not held in escrow.</p>
 <form onSubmit={load}><label htmlFor="recovery-order">Order ID<input id="recovery-order" value={orderId} onChange={event=>{setOrderId(event.target.value.trim());setRecord(null);setMessage('');}} pattern="0x[0-9a-fA-F]{64}" required disabled={!!busy} spellCheck={false}/></label><button className={s.secondary} disabled={!!busy}>{busy==='read'?'Reading recovery records…':'Read recovery records'}</button></form>
 {record && <><h3>Recorded evidence</h3><p>{record.disputes.length} dispute · {record.refunds.length} refund transfers · {record.reviews.length} independent reviews</p>{record.disputes.map((item,index)=><p key={index}>{item.reason}</p>)}{record.refunds.map(item=><p key={item.transaction_hash}><a href={`https://testnet.arcscan.app/tx/${item.transaction_hash}`} target="_blank" rel="noopener noreferrer">Refund receipt</a> · {item.amount_atomic} micro-USDC</p>)}
 {record.canDispute && !record.disputes.length && <form onSubmit={event=>void submit(event,'dispute')}><label htmlFor="dispute-reason">What went wrong?<textarea id="dispute-reason" value={reason} onChange={event=>setReason(event.target.value)} maxLength={2000} required disabled={!!busy}/></label><button className={s.secondary} disabled={!!busy}>{busy==='dispute'?'Recording dispute…':'Record dispute'}</button></form>}
 {record.canRefund && <form onSubmit={event=>void submit(event,'refund')}><h3>Attach an existing refund</h3><p>Send canonical USDC from the seller to the original payer first. Enter its finalized transfer below. This form sends no funds.</p><label htmlFor="refund-hash">Refund transaction hash<input id="refund-hash" value={hash} onChange={event=>setHash(event.target.value.trim())} pattern="0x[0-9a-fA-F]{64}" required disabled={!!busy}/></label><label htmlFor="refund-log">Transfer log index<input id="refund-log" type="number" min="0" step="1" value={logIndex} onChange={event=>setLogIndex(event.target.value)} required disabled={!!busy}/></label><label htmlFor="refund-amount">Amount in micro-USDC<input id="refund-amount" inputMode="numeric" pattern="[1-9][0-9]*" value={amount} onChange={event=>setAmount(event.target.value)} maxLength={78} required disabled={!!busy}/></label><button className={s.secondary} disabled={!!busy}>{busy==='refund'?'Verifying refund…':'Record completed refund'}</button></form>}</>}
 {error && <p className={e.formError} role="alert">{error}</p>}{message && <p role="status">{message}</p>}
 </div></details>;
}
