'use client';
import React,{useEffect,useState} from 'react';
import {api,errorMessage} from './api';
import type {PublicHederaEvidence} from '@/lib/hedera/public-evidence';
import h from './hedera-integrations.module.css';
const absent='No confirmed proof published';
const explorer=(kind:'transaction'|'topic'|'token'|'schedule',id:string)=>`https://hashscan.io/testnet/${kind}/${encodeURIComponent(id)}`;
function ProofLink({kind,id,children}:{kind:'transaction'|'topic'|'token'|'schedule';id:string;children:React.ReactNode}) {return <a href={explorer(kind,id)} target="_blank" rel="noopener noreferrer">{children}</a>;}
function Anchor({anchor}:{anchor:NonNullable<PublicHederaEvidence['release']>['audit']}) {
 if(!anchor)return <p className={h.status}>{absent}</p>;
 return <><dl className={h.detail}><dt>Topic</dt><dd><ProofLink kind="topic" id={anchor.topicId}>{anchor.topicId}</ProofLink></dd><dt>Sequence</dt><dd>{anchor.sequenceNumber}</dd><dt>Consensus time</dt><dd><code>{anchor.consensusTimestamp}</code></dd><dt>Submission</dt><dd><ProofLink kind="transaction" id={anchor.transactionId}>{anchor.transactionId}</ProofLink></dd></dl><div className={h.links}><a href={`https://testnet.mirrornode.hedera.com/api/v1/topics/${anchor.topicId}/messages/${anchor.sequenceNumber}`} target="_blank" rel="noopener noreferrer">Read topic message JSON</a></div></>;
}
function Identity({identity,label}:{identity:PublicHederaEvidence['identityService'];label:string}) {
 return <div className={h.identity}><h4>{label}</h4>{identity?<><p className={h.status}>{identity.profileAnchor?'Profile anchor published':'Identity configured · awaiting a profile anchor'}</p><dl className={h.detail}><dt>UAID</dt><dd><code>{identity.uaid}</code></dd><dt>Agent</dt><dd>{identity.canonical.name}</dd></dl><Anchor anchor={identity.profileAnchor}/></>:<p className={h.status}>{absent}</p>}</div>;
}
export function HederaEvidenceView({evidence}:{evidence:PublicHederaEvidence}) {
 const release=evidence.release;
 return <div className={h.view}>
  <div className={h.intro}><h2>Hedera service connections</h2><p>Discover the repository service, inspect its public identity and follow testnet payment evidence. Signing and payment journals stay in the private runner.</p><div className={h.links}><a href="/.well-known/agent-card.json" target="_blank" rel="noopener noreferrer">Agent Card JSON</a><a href="/api/hedera/evidence" target="_blank" rel="noopener noreferrer">Public evidence JSON</a><a href="https://github.com/saiisback/obolos/blob/main/docs/hedera-identity-audit.md" target="_blank" rel="noopener noreferrer">Identity and audit source</a></div>{release&&<p className={h.status}>Evidence published {new Date(release.checkedAt).toISOString().replace('T',' ').replace('.000Z',' UTC')}</p>}</div>
  <section className={h.section} aria-labelledby="hedera-a2a-heading"><div><h3 id="hedera-a2a-heading">Discovery and negotiation</h3></div><div><p>The A2A Agent Card advertises the service. A buyer proposes repository quantity and a price limit, then accepts an offer through the HBAR x402 paid resource request.</p><dl className={h.detail}><dt>Discovery</dt><dd><a href="/.well-known/agent-card.json">/.well-known/agent-card.json</a></dd><dt>A2A endpoint</dt><dd><code>POST /api/hedera/a2a</code></dd><dt>HBAR resource</dt><dd><code>POST /x402/evidence/repo-standard</code></dd></dl>{release?.a2a?<><p className={h.status}>Paid A2A response published</p><dl className={h.detail}><dt>Offer</dt><dd><code>{release.a2a.offerId}</code></dd><dt>Payment</dt><dd><ProofLink kind="transaction" id={release.a2a.receipt.transactionId}>{release.a2a.receipt.transactionId}</ProofLink></dd><dt>Resource cost</dt><dd>{release.a2a.receipt.amountAtomic} tinybar · {release.a2a.receipt.units} {release.a2a.receipt.units===1?'repository':'repositories'}</dd></dl></>:<p className={h.status}>{absent}</p>}</div></section>
  <section className={h.section} aria-labelledby="hedera-identity-heading"><div><h3 id="hedera-identity-heading">Agent identity</h3><p>HCS-14 identifiers with profile anchors on restricted-submit HCS topics.</p></div><div><Identity identity={evidence.identityService} label="Repository service"/><Identity identity={evidence.identityBuyer} label="Repository buyer"/></div></section>
  <section className={h.section} aria-labelledby="hedera-audit-heading"><div><h3 id="hedera-audit-heading">Payment audit</h3></div><div><p>The public topic message binds the agent identity to a settlement reference and compact request and evidence hashes.</p><Anchor anchor={release?.audit}/></div></section>
  <section className={h.section} aria-labelledby="hedera-token-heading"><div><h3 id="hedera-token-heading">Token-priced access</h3></div><div>{evidence.hts?<><p className={h.status}>Configured · Testnet service credit</p><p>This optional resource path uses a native Hedera token. The private operator handles payer association before purchasing access.</p><dl className={h.detail}><dt>Token</dt><dd><ProofLink kind="token" id={evidence.hts.asset}>{evidence.hts.symbol} · {evidence.hts.asset}</ProofLink></dd><dt>Unit price</dt><dd>{evidence.hts.unitPriceAtomic} atomic units per repository · {evidence.hts.decimals} decimals</dd><dt>Recipient</dt><dd><code>{evidence.hts.payTo}</code></dd><dt>Resource</dt><dd><code>POST /x402/hts/evidence/repo-standard</code></dd></dl>{release?.hts?<><p className={h.status}>Token payment proof published</p><ProofLink kind="transaction" id={release.hts.transactionId}>{release.hts.transactionId}</ProofLink></>:<p className={h.status}>{absent}</p>}</>:<p className={h.status}>{absent}</p>}</div></section>
  <section className={h.section} aria-labelledby="hedera-schedules-heading"><div><h3 id="hedera-schedules-heading">Scheduled access</h3></div><div><p>A finite owner-approved plan creates Hedera Scheduled Transactions. Each resource delivery uses a confirmed transfer once.</p>{release?.schedules?.length?<ul className={h.proofList}>{release.schedules.map(schedule=><li key={schedule.scheduleId}><dl className={h.detail}><dt>Schedule</dt><dd><ProofLink kind="schedule" id={schedule.scheduleId}>{schedule.scheduleId}</ProofLink></dd><dt>Transfer</dt><dd><ProofLink kind="transaction" id={schedule.transactionId}>{schedule.transactionId}</ProofLink></dd><dt>Resource cost</dt><dd>{schedule.proof.amountAtomic} tinybar</dd><dt>Recipient</dt><dd><code>{schedule.proof.payTo}</code></dd><dt>Consensus time</dt><dd><code>{schedule.proof.consensusTimestamp}</code></dd></dl></li>)}</ul>:<p className={h.status}>{absent}</p>}</div></section>
 </div>;
}
export function HederaIntegrations() {
 const [evidence,setEvidence]=useState<PublicHederaEvidence|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{setEvidence(await api<PublicHederaEvidence>('/api/hedera/evidence'));}catch(error){setError(errorMessage(error));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 if(loading)return <p role="status">Loading public Hedera evidence…</p>;
 if(error)return <div className={h.view}><p className={h.error} role="alert">{error}</p><div><button className={h.retry} onClick={()=>void load()}>Retry evidence</button></div></div>;
 return evidence?<HederaEvidenceView evidence={evidence}/>:null;
}
