import {describe,it,expect} from 'vitest';
import {encodeAbiParameters,encodeEventTopics,parseAbi,keccak256,toHex,type Address} from 'viem';
import {findFinalizedUserOperation,type UserOpRecoveryClient} from '../scripts/circle-userop-recovery';
const wallet='0x1111111111111111111111111111111111111111',entryPoint='0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789';
const hash=(s:string)=>keccak256(toHex(s));const userOpHash=hash('exact-userop'),txHash=hash('tx'),blockHash=hash('block');
const abi=parseAbi(['event UserOperationEvent(bytes32 indexed userOpHash,address indexed sender,address indexed paymaster,uint256 nonce,bool success,uint256 actualGasCost,uint256 actualGasUsed)']);
const log=(sender:Address=wallet,success=true)=>({address:entryPoint,topics:encodeEventTopics({abi,eventName:'UserOperationEvent',args:{userOpHash,sender,paymaster:'0x0000000000000000000000000000000000000000'}}),data:encodeAbiParameters([{type:'uint256'},{type:'bool'},{type:'uint256'},{type:'uint256'}],[1n,success,2n,3n]),transactionHash:txHash,blockNumber:1500n,blockHash,logIndex:0,removed:false});
function fixture(){let logs=[log()];const queries:unknown[]=[];const client={getBlock:async(args:{blockNumber?:bigint})=>({number:args.blockNumber??2000n,hash:blockHash}),readContract:async()=>entryPoint,getLogs:async(args:unknown)=>{queries.push(args);return logs;},getTransactionReceipt:async()=>({status:'success',transactionHash:txHash,blockHash,blockNumber:1500n,logs})};return {client,queries,setLogs:(values:typeof logs)=>{logs=values;}};}
describe('exact finalized Circle user operation recovery',()=>{
 it('finds only exact sender/hash at the wallet-bound entrypoint within a bounded range',async()=>{const s=fixture();expect(await findFinalizedUserOperation(s.client as unknown as UserOpRecoveryClient,wallet,userOpHash)).toBe(txHash);expect(s.queries).toEqual([expect.objectContaining({address:entryPoint,fromBlock:1n,toBlock:2000n,args:{userOpHash,sender:wallet}})]);});
 it.each(['wrong-sender','failed-operation','wrong-entrypoint','noncanonical-block','multiple-matches'])('rejects %s without deriving a replacement payment',async reason=>{const s=fixture();if(reason==='wrong-sender')s.setLogs([log('0x2222222222222222222222222222222222222222')]);if(reason==='failed-operation')s.setLogs([log(wallet,false)]);if(reason==='wrong-entrypoint')s.client.readContract=async()=>wallet;if(reason==='noncanonical-block')s.client.getBlock=async()=>({number:2000n,hash:hash('different')});if(reason==='multiple-matches')s.setLogs([log(),{...log(),transactionHash:hash('other')}]);await expect(findFinalizedUserOperation(s.client as unknown as UserOpRecoveryClient,wallet,userOpHash)).rejects.toThrow();});
 it('leaves an absent operation pending after one bounded read',async()=>{const s=fixture();s.setLogs([]);expect(await findFinalizedUserOperation(s.client as unknown as UserOpRecoveryClient,wallet,userOpHash)).toBeNull();expect(s.queries).toHaveLength(1);});
});
