import {describe,it,expect} from 'vitest';
import {calculateMeasurements,type MeasurementInput,type MeasurementService} from '../src/lib/economy/measurements';
import {resourceCategories,type EconomicSettlement} from '../src/lib/economy/model';
const day=5*86400,asOf=day+3600;
const order=(id:string,timestamp:number,changes:Partial<EconomicSettlement & {deliveredAt:number;acknowledgedAt:number}>={}):MeasurementInput['settlements'][number]=>({orderId:id,agentId:'agent1',seller:'seller',asset:'USDC',category:'compute',unit:'compute-unit-hash',quantity:1n,principalAtomic:100n,sellerAtomic:95n,timestamp,delivered:true,buyerAcknowledged:true,sameOwner:true,verifiedFinalOutputAtomic:null,verifiedIntermediateInputAtomic:null,valuationReference:null,deliveredAt:timestamp+1,acknowledgedAt:timestamp+2,...changes});
const services=():MeasurementService[]=>resourceCategories.map((category,index)=>({serviceHash:'base-'+category,seller:'seller-'+category,category,unitHash:'unit-'+category,quantity:'2',unitPrice:'100',endpointHash:'endpoint-'+category,registeredAt:day-2*86400-100+index,transactionHash:'tx-'+category}));
const input=(changes:Partial<MeasurementInput>={}):MeasurementInput=>({settlements:[],services:services(),agents:[{agentId:'agent1',executor:'WALLET',active:true}],balances:[{address:'wallet',balanceAtomic:1000n}],asOf,blockNumber:'123',blockHash:'block-hash',fromTimestamp:day-3*86400,...changes});
describe('observed economic measurements',()=>{
 it('counts UTC payment/refund boundaries and independent delivery event times without inventing valuations',()=>{const m=calculateMeasurements(input({settlements:[order('before',day-1,{deliveredAt:day,acknowledgedAt:day+1}),order('today',day),order('edge',asOf,{delivered:false,buyerAcknowledged:false}),order('future',asOf+1)],refunds:[{orderId:'before',amountAtomic:10n,timestamp:day-1},{orderId:'today',amountAtomic:20n,timestamp:day},{orderId:'today',amountAtomic:30n,timestamp:asOf+1}]}));expect(m.today).toMatchObject({settlementCount:2,grossPaymentsAtomic:200n,sellerRevenueAtomic:190n,refundAtomic:20n,deliveredCount:2,acknowledgedCount:2});expect(m.lifetime).toMatchObject({settlementCount:3,grossPaymentsAtomic:300n,refundAtomic:30n});expect(m.activity).toMatchObject({activeAgentCount:1,fulfilledAgentCount:1,utilizationBps:10000n});expect(m.activity.methodology).toContain('operational');});
 it('does not assign an unknown delivery time to today',()=>{const m=calculateMeasurements(input({settlements:[{...order('old',day-100),deliveredAt:undefined,acknowledgedAt:undefined}]}));expect(m.today.deliveredCount).toBe(0);expect(m.lifetime.deliveredCount).toBe(1);expect(m.activity.fulfilledAgentCount).toBe(0);});
 it('deduplicates active executor balances and marks missing funds unknown',()=>{const base=input({settlements:[order('o',day)],agents:[{agentId:'agent1',executor:'WALLET',active:true},{agentId:'agent2',executor:'wallet',active:true},{agentId:'agent3',executor:'inactive',active:false}],balances:[{address:'wallet',balanceAtomic:1000n},{address:'WALLET',balanceAtomic:1000n},{address:'inactive',balanceAtomic:5000n}]});expect(calculateMeasurements(base).capital).toMatchObject({executorCount:1,totalAtomic:1000n,todayTurnoverBps:1000n});expect(calculateMeasurements({...base,balances:[]}).capital).toMatchObject({totalAtomic:null,todayTurnoverBps:null,missingExecutorAddresses:['wallet']});});
 it('keeps zero denominators unavailable',()=>{const m=calculateMeasurements(input({agents:[],balances:[],services:[]}));expect(m.activity.utilizationBps).toBeNull();expect(m.capital).toMatchObject({totalAtomic:0n,todayTurnoverBps:null});expect(m.prices.indexBps).toBeNull();});
 it('pins each earliest quote family and rejects cheaper incompatible current offers',()=>{const base=services(),compute=base[1],changed={...compute,serviceHash:'changed',unitPrice:'300',registeredAt:day+1,transactionHash:'change-tx'};const unrelated={...changed,serviceHash:'unrelated',seller:'other',unitPrice:'1',registeredAt:day+2};const m=calculateMeasurements(input({services:[...base,changed,unrelated]}));expect(m.prices.indexBps).toBe(14000n);expect(m.prices.baselineChangeBps).toBe(4000n);expect(m.prices.components[1]).toMatchObject({category:'compute',familyServiceHash:compute.serviceHash,currentServiceHash:'changed',weightBps:2000n,currentAtomic:300n});expect(m.prices.purchasingPower[1]).toMatchObject({serviceHash:'changed',unitHash:compute.unitHash,unitsPerUsdcMillionths:3333333333n});});
 it('establishes the baseline only when all five families exist, at quotes actually available then',()=>{const base=services();base[4]={...base[4],registeredAt:day+10};const changed={...base[1],serviceHash:'before-completion',unitPrice:'300',registeredAt:day+5};const m=calculateMeasurements(input({services:[...base,changed]}));expect(m.prices).toMatchObject({baselineAt:day+10,indexBps:10000n,baselineChangeBps:0n,priorClosedDay:null,periodInflationBps:null});expect(m.prices.components[1].baselineServiceHash).toBe('before-completion');});
 it('uses only fully observed closed days for inflation and does not use future quotes',()=>{const base=services(),compute=base[1];const m=calculateMeasurements(input({services:[...base,{...compute,serviceHash:'yesterday',unitPrice:'200',registeredAt:day-1},{...compute,serviceHash:'today',unitPrice:'300',registeredAt:day},{...compute,serviceHash:'future',unitPrice:'900',registeredAt:asOf+1}]}));expect(m.prices.priorClosedDay).toMatchObject({start:day-86400,end:day,indexBps:12000n});expect(m.prices.periodInflationBps).toBe(2000n);expect(m.prices.changeSincePriorCloseBps).toBe(1666n);expect(m.prices.indexBps).toBe(14000n);});
 it('preserves event order for same-second offers, input arrays and reproducible source hashes',()=>{const base=services(),compute=base[1],rows=[...base,{...compute,serviceHash:'z-first',unitPrice:'200',registeredAt:day},{...compute,serviceHash:'a-second',unitPrice:'300',registeredAt:day}];const before=rows.map(s=>s.serviceHash);const m=calculateMeasurements(input({services:rows}));expect(rows.map(s=>s.serviceHash)).toEqual(before);expect(m.prices.components[1].currentServiceHash).toBe('a-second');expect(calculateMeasurements(input({services:rows})).provenance.inputHash).toBe(m.provenance.inputHash);expect(m.provenance.blockHash).toBe('block-hash');});
});

it('pins first-complete basket at its event position before later same-second changes',()=>{const base=services();base[4]={...base[4],registeredAt:day};const later={...base[1],serviceHash:'later-same-second',registeredAt:day,unitPrice:'200'};const m=calculateMeasurements(input({services:[...base,later]}));expect(m.prices.components[1].baselineServiceHash).toBe('base-compute');expect(m.prices.indexBps).toBe(12000n);});
it('accepts precise refund record times and ignores later records without deduping transfer logs',()=>{const m=calculateMeasurements(input({settlements:[order('paid',day)],refunds:[{orderId:'paid',amountAtomic:10n,timestamp:day+0.125,transactionHash:'same-tx',logIndex:0},{orderId:'paid',amountAtomic:20n,timestamp:day+0.125,transactionHash:'same-tx',logIndex:1},{orderId:'paid',amountAtomic:30n,timestamp:asOf+0.001}]}));expect(m.today.refundAtomic).toBe(30n);expect(m.today.refundCount).toBe(2);});
