import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {describe,it,expect} from 'vitest';
import {keccak256,toHex} from 'viem';
import {runEconomyExecutor,type ExecutorDependencies,type ExecutorInput} from '../src/lib/economy/executor';
import {createServiceDefinition,canonicalJsonHash} from '../src/lib/economy/service-contract';
const hash=(s:string)=>keccak256(toHex(s));
const owner='0x1111111111111111111111111111111111111111',payer='0x2222222222222222222222222222222222222222';
const definition=createServiceDefinition({chainId:5042002,settlementAddress:'0x3333333333333333333333333333333333333333',ledgerAddress:'0x4444444444444444444444444444444444444444',seller:'0x5555555555555555555555555555555555555555',endpoint:'https://obolos.app/api/economy/reference/compute',category:'compute',unit:'compute-unit',quantity:'1',unitPriceAtomic:'1000',inputSchema:{type:'object',properties:{},additionalProperties:false},outputSchema:{type:'object',properties:{},additionalProperties:false}});
const input:ExecutorInput={version:1,origin:'https://obolos.app',platformAgentId:'12345678-1234-4234-8234-123456789012',orderId:hash('permanent-order'),owner,payer,definition,serviceHash:definition.serviceHash,input:{},maxAmountAtomic:'1000',expiry:'2000000000'};
async function setup(){const directory=await mkdtemp(join(tmpdir(),'executor-'));const actions:string[]=[];const requests:unknown[]=[];const deps:ExecutorDependencies={async prepareApproval(){},async preparePayment(){},async assertActiveService(){},async hasOperation(){return true;},async prepareAbort(){throw Error("abort not configured");},async abort(){throw Error("abort not configured");},async verifyAborted(){},async authenticate(){},async preflight(){return {policyVersion:'1',agentVersion:'2',feeVersion:'1'};},async approve(state){actions.push('approve');const stored=JSON.parse(await readFile(join(directory,state.intent.orderId+'.json'),'utf8'));expect(stored.phase).toBe('approving');},async pay(){actions.push('pay');return hash('payment');},async recover(){throw Error('uncertain');},async verifyPayment(){},async deliver(request){requests.push(request);return {orderId:request.orderId,serviceHash:request.serviceHash,transactionHash:request.settlement.transactionHash,state:'fulfilled',output:{},outputHash:canonicalJsonHash({})};},async verifyDelivery(){return false;},async acknowledge(){actions.push('ack');return hash('ack');}};return {directory,actions,requests,deps};}
describe('durable economy executor',()=>{
 it('persists before spending, then delivers and acknowledges',async()=>{const s=await setup();const result=await runEconomyExecutor(input,s.directory,s.deps);expect(result.phase).toBe('completed');expect(s.actions).toEqual(['approve','pay','ack']);});
 it('never repays after a delivery failure and reuses the exact request',async()=>{const s=await setup(),deliver=s.deps.deliver;let calls=0;s.deps.deliver=async request=>{if(calls++===0){s.requests.push(request);throw Error('provider pending');}return deliver(request);};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('provider pending');await runEconomyExecutor(input,s.directory,s.deps);expect(s.actions).toEqual(['approve','pay','ack']);expect(s.requests[0]).toEqual(s.requests[1]);});
 it('rejects changed input on a paid retry',async()=>{const s=await setup();s.deps.deliver=async()=>{throw Error('pending');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow();await expect(runEconomyExecutor({...input,maxAmountAtomic:'2000'},s.directory,s.deps)).rejects.toThrow('immutable');expect(s.actions).toEqual(['approve','pay']);});
 it('rejects a cross-agent key before any payment',async()=>{const s=await setup();s.deps.authenticate=async()=>{throw Error('KEY_SCOPE_MISMATCH');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('KEY_SCOPE_MISMATCH');expect(s.actions).toEqual([]);});
 it('does not resubmit an uncertain payment',async()=>{const s=await setup();s.deps.pay=async()=>{s.actions.push('pay');throw Error('uncertain');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('uncertain');await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('uncertain');expect(s.actions).toEqual(['approve','pay']);});
 it('blocks other orders while an allowance or payment is unresolved',async()=>{const s=await setup();s.deps.pay=async()=>{throw Error('uncertain');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow();await expect(runEconomyExecutor({...input,orderId:hash('different')},s.directory,s.deps)).rejects.toThrow('reservation');expect(s.actions).toEqual(['approve']);});
 it('refuses to acknowledge output without onchain seller evidence',async()=>{const s=await setup();s.deps.verifyDelivery=async()=>{throw Error('No seller delivery');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('No seller delivery');expect(s.actions).toEqual(['approve','pay']);});
 it('rejects policy or cap failures before allowance',async()=>{const s=await setup();s.deps.preflight=async()=>{throw Error('policy rejected');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('policy rejected');expect(s.actions).toEqual([]);});
});

import {assertExecutorPolicy,type ExecutorPolicySnapshot} from '../src/lib/economy/executor-live';
const policySnapshot=():ExecutorPolicySnapshot=>({agent:[owner,payer,true,5000n,1000n,3000n,60n],boundOwner:owner,allowed:true,category:[true,2000n,3000n,60n,0n],enabled:true,service:[definition.seller,1,keccak256(toHex(definition.unit)),1n,1000n,keccak256(toHex(definition.endpoint))],marker:'0x'+'0'.repeat(64)});
describe('live spending policy validation',()=>{
 it('accepts an exact existing mandate and service',()=>{expect(()=>assertExecutorPolicy(input,policySnapshot())).not.toThrow();});
 it.each(['owner','executor','boundOwner','active','sellerAllowed','categoryEnabled','marketEnabled','orderCap','totalCap','agentWindowCap','categoryWindowCap','seller','price','consumed'])('rejects %s mismatch before allowance',field=>{const s=policySnapshot();switch(field){case'owner':s.agent[0]=payer;break;case'executor':s.agent[1]=owner;break;case'boundOwner':s.boundOwner=payer;break;case'active':s.agent[2]=false;break;case'sellerAllowed':s.allowed=false;break;case'categoryEnabled':s.category[0]=false;break;case'marketEnabled':s.enabled=false;break;case'orderCap':s.category[1]=999n;break;case'totalCap':s.agent[3]=1999n;break;case'agentWindowCap':s.agent[5]=999n;break;case'categoryWindowCap':s.category[2]=999n;break;case'seller':s.service[0]=owner;break;case'price':s.service[4]=2000n;break;case'consumed':s.marker=hash('consumed');break;}expect(()=>assertExecutorPolicy(input,s)).toThrow(/rejected|mismatch|consumed/);});
});

describe('executor recovery evidence',()=>{
 it('does not call acknowledgment complete when recovery lacks final chain acknowledgment',async()=>{const s=await setup();s.deps.acknowledge=async()=>{throw Error('ack uncertain');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('ack uncertain');s.deps.recover=async()=>hash('ack');await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('Acknowledgment not finalized');});
 it('does not need an active offer or fresh policy after payment',async()=>{const s=await setup(),deliver=s.deps.deliver;s.deps.deliver=async()=>{throw Error('pending');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('pending');s.deps.deliver=deliver;s.deps.preflight=async()=>{throw Error('offer retired');};expect((await runEconomyExecutor(input,s.directory,s.deps)).phase).toBe('completed');expect(s.actions).toEqual(['approve','pay','ack']);});
});

describe('executor pre-submit safety',()=>{
 it('keeps a failed allowance precheck retryable without reserving the wallet',async()=>{const s=await setup();s.deps.prepareApproval=async()=>{throw Error('Insufficient balance');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('Insufficient balance');expect(JSON.parse(await readFile(join(s.directory,input.orderId+'.json'),'utf8')).phase).toBe('prepared');await expect(readFile(join(s.directory,'allowance-reservation.json'))).rejects.toMatchObject({code:'ENOENT'});s.deps.prepareApproval=async()=>{};expect((await runEconomyExecutor(input,s.directory,s.deps)).phase).toBe('completed');});
 it('keeps a failed settlement simulation approved and retries without a second approval',async()=>{const s=await setup();s.deps.preparePayment=async()=>{throw Error('RPC unavailable');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('RPC unavailable');expect(JSON.parse(await readFile(join(s.directory,input.orderId+'.json'),'utf8')).phase).toBe('approved');s.deps.preparePayment=async()=>{};await runEconomyExecutor(input,s.directory,s.deps);expect(s.actions).toEqual(['approve','pay','ack']);});
 it('does not pay if the scoped key is revoked while approval finalizes',async()=>{const s=await setup(),approve=s.deps.approve;let revoked=false;s.deps.authenticate=async()=>{if(revoked)throw Error('revoked key');};s.deps.approve=async state=>{await approve(state);revoked=true;};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('revoked key');expect(s.actions).toEqual(['approve']);});
 it('does not pay if the exact offer retires while approval finalizes',async()=>{const s=await setup(),approve=s.deps.approve;s.deps.approve=async state=>{await approve(state);s.deps.assertActiveService=async()=>{throw Error('offer retired');};};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('offer retired');expect(s.actions).toEqual(['approve']);});
 it('resumes the original action only after durable evidence proves no submission occurred',async()=>{const s=await setup(),pay=s.deps.pay;let first=true;s.deps.hasOperation=async()=>false;s.deps.pay=async state=>{if(first){first=false;throw Error('failed before journal');}return pay(state);};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow('failed before journal');expect(JSON.parse(await readFile(join(s.directory,input.orderId+'.json'),'utf8')).phase).toBe('approved');await runEconomyExecutor(input,s.directory,s.deps);expect(s.actions).toEqual(['approve','pay','ack']);});
 it('explicitly aborts an approved unpaid order and releases its reservation only after verified revocation',async()=>{const s=await setup();s.deps.preparePayment=async()=>{throw Error('payment blocked');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow();s.deps.prepareAbort=async()=>true;s.deps.hasOperation=async(_state,kind)=>kind!=='abort';s.deps.abort=async()=>{s.actions.push('revoke');return hash('revoke');};s.deps.verifyAborted=async()=>{};const result=await runEconomyExecutor(input,s.directory,s.deps,{abortUnpaid:true});expect(result.phase).toBe('aborted');expect(s.actions).toEqual(['approve','revoke']);await expect(readFile(join(s.directory,'allowance-reservation.json'))).rejects.toMatchObject({code:'ENOENT'});});
 it('does not release a reservation when abort evidence cannot exclude a payment',async()=>{const s=await setup();s.deps.pay=async()=>{throw Error('uncertain payment');};await expect(runEconomyExecutor(input,s.directory,s.deps)).rejects.toThrow();s.deps.prepareAbort=async()=>{throw Error('payment journal exists');};await expect(runEconomyExecutor(input,s.directory,s.deps,{abortUnpaid:true})).rejects.toThrow('payment journal exists');expect(JSON.parse(await readFile(join(s.directory,'allowance-reservation.json'),'utf8')).orderId).toBe(input.orderId);});
});

import {withExecutorOperationLock} from '../src/lib/economy/executor-live';
describe('Circle operation synchronization',()=>{
 it('refuses an absence conclusion while the durable submit lock is held',async()=>{const s=await setup();let unlock!:()=>void;const gate=new Promise<void>(r=>{unlock=r;});let entered!:()=>void;const ready=new Promise<void>(r=>{entered=r;});const first=withExecutorOperationLock(s.directory,'same-payment',async()=>{entered();await gate;return 'first';});await ready;try{await expect(withExecutorOperationLock(s.directory,'same-payment',async()=>false)).rejects.toThrow('Circle operation locked');}finally{unlock();await first;}expect(await withExecutorOperationLock(s.directory,'same-payment',async()=>false)).toBe(false);});
});
