import {describe,it,expect} from 'vitest';
import {calculateEconomyMetrics} from '../src/lib/economy/metrics';
import type {EconomicSettlement,MetricWindow,PriceComponent} from '../src/lib/economy/model';
const prices:PriceComponent[]=[{id:'check',category:'verification',unit:'report',asset:'USDC',baselineAtomic:50n,currentAtomic:60n,weightBps:10000n}];
const priorBasketIdentity=JSON.stringify([['check','verification','report','USDC','50','10000','check']]);
const window:MetricWindow={start:10,end:20,asset:'USDC',activeAgentIds:['agent'],capitalAtomic:100n,previousArpi:{methodology:'obolos-agentgdp-v1',asset:'USDC',end:10,basketIdentity:priorBasketIdentity,arpiBps:11000n}};
const order:EconomicSettlement={orderId:'one',agentId:'agent',seller:'seller',asset:'USDC',category:'verification',unit:'report',quantity:1n,principalAtomic:60n,sellerAtomic:57n,timestamp:15,delivered:true,buyerAcknowledged:true,sameOwner:false,verifiedFinalOutputAtomic:100n,verifiedIntermediateInputAtomic:60n,valuationReference:'attestation:1'};
describe('paper-based economic measurement',()=>{
 it('separates baseline index, period inflation and paper velocity from turnover',()=>{const m=calculateEconomyMetrics([order],prices,window);expect(m.arpiBps).toBe(12000n);expect(m.baselineChangeBps).toBe(2000n);expect(m.inflationBps).toBe(909n);expect(m.gapAtomic).toBe(40n);expect(m.moneyVelocityBps).toBe(4000n);expect(m.paymentTurnoverBps).toBe(6000n);expect(m.productivityBps).toBe(16666n);});
 it('never sums HBAR with USDC or infers useful output from delivery',()=>{const m=calculateEconomyMetrics([{...order,verifiedFinalOutputAtomic:null},{...order,orderId:'h',asset:'HBAR',principalAtomic:999999n}],prices,window);expect(m.grossPaymentsAtomic).toBe(60n);expect(m.gapAtomic).toBeNull();expect(m.moneyVelocityBps).toBeNull();expect(m.valuedSettlementCount).toBe(0);});
 it('leaves incomplete baskets unavailable without silently changing weights',()=>{expect(calculateEconomyMetrics([], [{...prices[0],weightBps:5000n},{...prices[0],id:'other',currentAtomic:null,weightBps:5000n}],window).arpiBps).toBeNull();});
 it('only reports period inflation for a consecutive comparable basket observation',()=>{for(const previousArpi of [{...window.previousArpi!,end:9},{...window.previousArpi!,asset:'HBAR' as const},{...window.previousArpi!,basketIdentity:'different'}]){const m=calculateEconomyMetrics([],prices,{...window,previousArpi});expect(m.inflationBps).toBeNull();expect(m.limitations).toContain('Period inflation requires the immediately preceding ARPI observation for the same asset, methodology and fixed basket.');}});
 it('rejects duplicates, invalid windows and weights',()=>{expect(()=>calculateEconomyMetrics([order,order],prices,window)).toThrow();expect(()=>calculateEconomyMetrics([],prices,{...window,end:9})).toThrow();expect(()=>calculateEconomyMetrics([],[{...prices[0],weightBps:0n}],window)).toThrow();});
 it('does not compare inflation after replacing the basket source',()=>expect(calculateEconomyMetrics([], [{...prices[0],sourceReference:'a-different-service'}],window).inflationBps).toBeNull());
 it('excludes known self-payments, unacknowledged valuations, and missing references',()=>{const m=calculateEconomyMetrics([{...order,sameOwner:true}],prices,window);expect(m.gapAtomic).toBeNull();expect(m.excludedSelfPayments).toBe(1);expect(m.utilizationBps).toBe(0n);expect(calculateEconomyMetrics([{...order,valuationReference:null}],prices,window).gapAtomic).toBeNull();});
 it('uses half-open windows and exact integer amounts beyond JS precision',()=>{const large=900719925474099300000n;const m=calculateEconomyMetrics([{...order,principalAtomic:large},{...order,orderId:'late',timestamp:20}],prices,window);expect(m.grossPaymentsAtomic).toBe(large);expect(m.settlementCount).toBe(1);});
 it('does not manufacture utilization or economic data for an empty sample',()=>{const m=calculateEconomyMetrics([],[],{...window,activeAgentIds:[],capitalAtomic:null});expect(m.utilizationBps).toBeNull();expect(m.arpiBps).toBeNull();expect(m.gapAtomic).toBeNull();});
});
