import {randomUUID} from 'node:crypto';
import {readFile,readdir} from 'node:fs/promises';
import pg from 'pg';
import {afterAll,beforeAll,describe,expect,it,vi} from 'vitest';
import {keccak256,toHex} from 'viem';
const transport=vi.hoisted(()=>({query:undefined as unknown}));
vi.mock('../src/lib/platform/db',()=>({sql:()=>transport.query}));
vi.mock('../src/lib/economy/remote-service',()=>({requestRemoteService:async({request}:{request:{orderId:string;serviceHash:string;inputHash:string}})=>({protocol:'obolos.service.v1',orderId:request.orderId,serviceHash:request.serviceHash,inputHash:request.inputHash,outputHash:keccak256(toHex('{"result":"done"}')),output:{result:'done'}})}));
import {createEconomyOrder,createEconomyService,getEconomyOrder} from '../src/lib/economy/marketplace';
import {canonicalJsonHash,createServiceDefinition,serviceRequestSchema} from '../src/lib/economy/service-contract';

describe.skipIf(!process.env.TEST_DATABASE_URL)('PostgreSQL generic economy market',()=>{
 let admin:pg.Pool,pool:pg.Pool;const schema=`obolos_economy_${randomUUID().replaceAll('-','')}`,userId=randomUUID(),agentId=randomUUID();
 const address=(digit:string)=>`0x${digit.repeat(40)}` as `0x${string}`,hash=(text:string)=>keccak256(toHex(text));
 const user={id:userId,address:address('a'),createdAt:new Date().toISOString()};
 const deployment={chainId:5042002 as const,policy:address('9'),ledger:address('2'),settlement:address('1'),fromBlock:'1',controller:address('8'),approver:address('7'),reserve:address('6'),reviewPool:address('5')};
 beforeAll(async()=>{admin=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});await admin.query(`CREATE SCHEMA ${schema}`);pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL,options:`-c search_path=${schema}`});for(const name of(await readdir('db/migrations')).filter(name=>name.endsWith('.sql')).sort())await pool.query(await readFile(`db/migrations/${name}`,'utf8'));type Query={text:string;values:unknown[];then:PromiseLike<pg.QueryResultRow[]>['then']};const query=(parts:TemplateStringsArray,...values:unknown[]):Query=>{const text=parts.reduce((sum,part,index)=>sum+(index?`$${index}`:'')+part,'');return {text,values,then(resolve,reject){return pool.query(text,values).then(result=>result.rows).then(resolve,reject);}};};transport.query=query;await pool.query('INSERT INTO platform_users(id,address) VALUES($1,$2)',[userId,user.address]);await pool.query("INSERT INTO platform_agents(id,user_id,name,data_budget_atomic,verification_budget_atomic) VALUES($1,$2,'Agent',0,1000000)",[agentId,userId]);});
 afterAll(async()=>{await pool?.end();if(admin){await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await admin.end();}});
 it('keeps definitions immutable and paid delivery replayable without exposing input',async()=>{const definition=createServiceDefinition({chainId:5042002,settlementAddress:deployment.settlement,ledgerAddress:deployment.ledger,seller:user.address,endpoint:'https://compute.obolos.app/v1/run',category:'compute',unit:'compute-unit',quantity:'1',unitPriceAtomic:'50000',inputSchema:{type:'object',properties:{task:{type:'string',maxLength:100}},required:['task'],additionalProperties:false},outputSchema:{type:'object',properties:{result:{type:'string',maxLength:100}},required:['result'],additionalProperties:false}}),chain={deployment,readService:async()=>({seller:user.address,category:1,unitHash:hash('compute-unit'),quantity:1n,unitPrice:50000n,endpointHash:hash(definition.endpoint)})};await createEconomyService(user,definition,chain);await expect(createEconomyService(user,{...definition,inputSchema:{type:'null'}},chain)).rejects.toMatchObject({code:'SERVICE_IMMUTABLE'});
  expect(await createEconomyService(user,JSON.parse(JSON.stringify(definition)),chain)).toEqual(definition);
  const input={task:'render'},request=serviceRequestSchema.parse({protocol:'obolos.service.v1',orderId:hash('order'),agentId:hash(agentId),payer:address('b'),serviceHash:definition.serviceHash,inputHash:canonicalJsonHash(input),category:'compute',unit:'compute-unit',quantity:'1',unitPriceAtomic:'50000',amountAtomic:'50000',settlement:{chainId:5042002,address:deployment.settlement,ledgerAddress:deployment.ledger,transactionHash:hash('transaction')},input}),receipt={chainId:5042002,status:'success' as const,transactionHash:request.settlement.transactionHash,logs:[]};const order=await createEconomyOrder(user,{platformAgentId:agentId,request},{deployment,readAgent:async()=>({owner:user.address,executor:address('f'),active:false}),getFinalizedReceipt:async()=>receipt,verifySettlement:()=>({chainId:5042002,orderId:request.orderId,transactionHash:request.settlement.transactionHash,serviceHash:definition.serviceHash,inputHash:request.inputHash})});expect(order.state).toBe('fulfilled');expect(await getEconomyOrder(user.id,request.orderId)).not.toHaveProperty('request');expect((await pool.query('SELECT request,state FROM economy_orders WHERE order_id=$1',[request.orderId])).rows[0]).toMatchObject({request,state:'fulfilled'});
 });
});
