import {expect,it} from 'vitest';
import {classifyRunnerStatus} from '../src/lib/platform/execution';
import {createRun} from '../src/lib/engine';
const proofs=[{network:'hedera:testnet'},{network:'arc:testnet'}];
function negative(){const r=createRun({mode:'live',repos:['openai/codex']});r.status='failed';r.stage='verification';r.error='The paid verification found invalid evidence. Review the recorded receipt and failed checks.';r.report={title:'Report',summary:'Report',recommendation:'Review',evidence:[],generatedBy:'model',createdAt:r.createdAt,checks:[{label:'Metrics',passed:false,detail:'Wrong count'}],verified:false};r.receipts=[{id:'data',requestId:`${r.id}:data`,mode:'live',network:'hedera:testnet',asset:'HBAR',amountAtomic:100000,units:1,provider:'repo-standard',status:'settled',timestamp:r.createdAt,transactionId:'0.0.123@1.1'},{id:'verify',requestId:`${r.id}:verify`,mode:'live',network:'arc:testnet',asset:'USDC',amountAtomic:1000,units:1,provider:'arc-verifier',status:'settled',timestamp:r.createdAt,transactionId:`0x${'1'.repeat(64)}`}];return r;}
it('classifies independently confirmed negative verification as failed',()=>expect(classifyRunnerStatus(negative(),proofs)).toBe('failed'));
it.each([null,[],[{network:'arc:testnet'}],[{network:'hedera:testnet'}]])('keeps unproven payment status uncertain: %s',proof=>expect(classifyRunnerStatus(negative(),proof)).toBe('uncertain'));
it('keeps timeout and recovery errors uncertain even with existing proofs',()=>{const r=negative();r.error='Confirmation timeout: reconcile pending operation';expect(classifyRunnerStatus(r,proofs)).toBe('uncertain');});
it('requires returned negative checks and both recorded receipts',()=>{const r=negative();r.report!.checks=[];expect(classifyRunnerStatus(r,proofs)).toBe('uncertain');r.report!.checks=[{label:'Metric',passed:false,detail:'Bad'}];r.receipts.pop();expect(classifyRunnerStatus(r,proofs)).toBe('uncertain');});
it('preserves completed, blocked and no-spend failed status',()=>{const r=negative();r.status='completed';expect(classifyRunnerStatus(r)).toBe('succeeded');r.status='paused';expect(classifyRunnerStatus(r)).toBe('blocked');r.status='failed';r.stage='mandate';r.receipts=[];expect(classifyRunnerStatus(r)).toBe('failed');});
