import {expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {privateKeyToAccount} from 'viem/accounts';
import {mandateMessage} from '../src/lib/platform/execution-contracts';
import {assertMarketAuthorization} from '../src/lib/integrations/marketplace';
const owner=privateKeyToAccount(`0x${'31'.repeat(32)}`);
async function fixture(){const id=randomUUID(),jobId=randomUUID();const m={id:randomUUID(),agentId:randomUUID(),owner:owner.address,origin:'https://obolos.app',repos:['owner/repo'],allowedProviders:['repo-standard'],dataBudgetAtomic:100000,verificationBudgetAtomic:70000,maxDataUnitPriceAtomic:100000,maxRuns:1,expiresAt:new Date(Date.now()+3600000).toISOString(),verificationService:{id,revision:1,name:'Seller',recipient:`0x${'39'.repeat(20)}`,priceAtomic:60000,endpoint:`https://obolos.app/api/market/services/${id}`}};const message=mandateMessage(m);const report={title:'Report',summary:'owner/repo | stars=1 | forks=2 | openIssues=3',recommendation:'Review',evidence:[{repo:'owner/repo',description:'',stars:1,forks:2,openIssues:3,pushedAt:new Date().toISOString(),language:'TS',license:'MIT',sourceUrl:'https://api.github.com/repos/owner/repo',fetchedAt:new Date().toISOString()}],generatedBy:'model' as const,createdAt:new Date().toISOString(),checks:[],verified:false};return {input:{runId:jobId,requestId:`${jobId}:verify`,maxAmountAtomic:60000,mandateExpiresAt:m.expiresAt,report,market:{mandate:{...m,message,signature:await owner.signMessage({message})},runnerToken:`ob_runner_${'a'.repeat(43)}`}},env:{MARKETPLACE_URL:'https://obolos.app',MARKETPLACE_OWNER_ADDRESS:owner.address}};}
it('requires an independently pinned marketplace owner before accepting a different payee',async()=>{const {input,env}=await fixture();expect((await assertMarketAuthorization(input,env)).recipient).toBe(input.market.mandate.verificationService.recipient);await expect(assertMarketAuthorization(input,{})).rejects.toThrow();await expect(assertMarketAuthorization(input,{...env,MARKETPLACE_OWNER_ADDRESS:`0x${'41'.repeat(20)}`})).rejects.toThrow();});
it('refuses amount, run, origin and recipient substitution before any network call',async()=>{const {input,env}=await fixture();for(const changed of [{maxAmountAtomic:60001},{requestId:'different:verify'},{runId:'../../escape'},{market:{...input.market,mandate:{...input.market.mandate,verificationService:{...input.market.mandate.verificationService,recipient:owner.address}}}}])await expect(assertMarketAuthorization({...input,...changed},env)).rejects.toThrow();await expect(assertMarketAuthorization(input,{...env,MARKETPLACE_URL:'http://attacker.example'})).rejects.toThrow();});
