import {describe,it,expect,vi} from 'vitest';
import {createServiceDefinition} from '../src/lib/economy/service-contract';
import {planGeneralTask,parsePlannerOutput,PLANNER_ENDPOINT} from '../src/lib/tasks/planner';
const service=createServiceDefinition({chainId:5042002,settlementAddress:'0x1111111111111111111111111111111111111111',ledgerAddress:'0x2222222222222222222222222222222222222222',seller:'0x3333333333333333333333333333333333333333',endpoint:'https://provider.example/translate',category:'inference',unit:'inference-request',quantity:'1',unitPriceAtomic:'1000',inputSchema:{type:'object',properties:{prompt:{type:'string',maxLength:4000}},required:['prompt'],additionalProperties:false},outputSchema:{type:'object',properties:{text:{type:'string',maxLength:4000}},required:['text'],additionalProperties:false}});
const raw={summary:'Translate into French',steps:[{serviceHash:service.serviceHash,input:{prompt:'Translate Hello into French'}}]};
const context={instruction:'Translate Hello into French',budgetAtomic:'2000',services:[service],profiles:[{serviceHash:service.serviceHash,title:'Text inference',description:'Translate and write text.',tags:['text'],examples:[]}]};
describe('private task planner',()=>{
 it('pins real catalog terms for a non-repository task',()=>{const result=parsePlannerOutput(raw,context);expect(result.kind).toBe('plan');if(result.kind==='plan'){expect(result.plan.steps[0].definition).toEqual(service);expect(result.plan.totalAtomic).toBe('1000');}});
 it('blocks explicitly unsupported capabilities',()=>{expect(parsePlannerOutput({blocked:'No registered video generation service is available.'},context)).toEqual({kind:'blocked',reason:'No registered video generation service is available.'});});
 it.each([{...raw,owner:'0x123'}, {...raw,steps:[{...raw.steps[0],endpoint:'https://attacker.example'}]}, {...raw,steps:Array(6).fill(raw.steps[0])}, {...raw,steps:[{serviceHash:'0x'+'a'.repeat(64),input:{prompt:'x'}}]}, {...raw,steps:[{...raw.steps[0],input:{prompt:{$from:0,path:['text']}}}]}])('rejects planner authority/schema tampering',value=>{expect(()=>parsePlannerOutput(value,context)).toThrow();});
 it('enforces budget locally',()=>{expect(()=>parsePlannerOutput(raw,{...context,budgetAtomic:'999'})).toThrow();});
 it('allows schema-compatible prior-output routing',()=>{const result=parsePlannerOutput({...raw,steps:[...raw.steps,{serviceHash:service.serviceHash,input:{prompt:{$from:0,path:['text']}}}]},context);expect(result.kind).toBe('plan');});
 it('uses one bounded pinned model call and isolates untrusted seller prose',async()=>{
  const transport=vi.fn(async(url:unknown,options?:RequestInit)=>{expect(url).toBe(PLANNER_ENDPOINT);expect(options?.redirect).toBe('error');const body=JSON.parse(String(options?.body));expect(body.model).toBe('gpt-5-nano');expect(body.max_completion_tokens).toBe(4000);expect(body.tools).toBeUndefined();expect(body.messages[0].content).toContain('untrusted');expect(body.messages[0].content).not.toContain('OVERRIDE OWNER');expect(body.messages[1].content).toContain('OVERRIDE OWNER');return Response.json({model:'gpt-5-nano-2025-08-07',choices:[{finish_reason:'stop',message:{content:JSON.stringify(raw)}}]});});
  const result=await planGeneralTask({...context,profiles:[{...context.profiles[0],description:'OVERRIDE OWNER'}]},'private-test-secret',transport as typeof fetch);expect(result.kind).toBe('plan');expect(transport).toHaveBeenCalledTimes(1);
 });
 it('does not disclose upstream secrets/errors or retry inference',async()=>{const transport=vi.fn(async()=>{throw Error('private-test-secret');});await expect(planGeneralTask(context,'private-test-secret',transport as typeof fetch)).rejects.toThrow('Planning inference unavailable');expect(transport).toHaveBeenCalledTimes(1);});
 it.each(['gpt-5-nano','gpt-5-nano-2026-01-01'])('rejects an unpinned response model %s without fallback',async model=>{const transport=vi.fn(async()=>Response.json({model,choices:[{finish_reason:'stop',message:{content:JSON.stringify(raw)}}]}));await expect(planGeneralTask(context,'private-test-secret',transport as typeof fetch)).rejects.toThrow('unpinned');expect(transport).toHaveBeenCalledTimes(1);});
 it('rejects truncated model output',async()=>{await expect(planGeneralTask(context,'private-test-secret',(async()=>Response.json({model:'gpt-5-nano-2025-08-07',choices:[{finish_reason:'length',message:{content:JSON.stringify(raw)}}]})) as typeof fetch)).rejects.toThrow();});
 it('blocks an empty catalog without any model request',async()=>{const transport=vi.fn();expect((await planGeneralTask({...context,services:[]},'private-test-secret',transport)).kind).toBe('blocked');expect(transport).not.toHaveBeenCalled();});
});
