import Link from 'next/link';
import { PlatformShell } from '@/components/platform/shell';
import s from '@/components/platform/platform.module.css';

const setup = `export OBOLOS_URL="https://obolos.app"
export AGENT_ID="your-agent-id"
# Paste the one-time credential from your workspace.
read -r -s OBOLOS_API_KEY
export OBOLOS_API_KEY`;
const list = `curl --fail-with-body \\
  "$OBOLOS_URL/api/v1/agents/$AGENT_ID/runs" \\
  -H "Authorization: Bearer $OBOLOS_API_KEY"`;
const create = `curl --fail-with-body -X POST \\
  "$OBOLOS_URL/api/v1/agents/$AGENT_ID/runs" \\
  -H "Authorization: Bearer $OBOLOS_API_KEY" \\
  -H "Content-Type: application/json" \\
  -H "Idempotency-Key: repo-review-001" \\
  --data '{"repos":["octocat/Hello-World"]}'`;
const detail = `export RUN_ID="job-id-returned-by-the-api"
curl --fail-with-body \\
  "$OBOLOS_URL/api/v1/agents/$AGENT_ID/runs/$RUN_ID" \\
  -H "Authorization: Bearer $OBOLOS_API_KEY"`;
const marketOrder = `curl --fail-with-body -X POST \\
  "$OBOLOS_URL/api/market/orders" \\
  -H "Authorization: Bearer $RUNNER_TOKEN" \\
  -H "Content-Type: application/json" \\
  --data '{"jobId":"job-id","payer":"0x…","report":{},"dataTransactionId":"0.0.123@1234567890.000000001"}'`;
const confirmOrder = `curl --fail-with-body -X POST \\
  "$OBOLOS_URL/api/market/orders/$ORDER_ID/confirm" \\
  -H "Authorization: Bearer $RUNNER_TOKEN" \\
  -H "Content-Type: application/json" \\
  --data '{"transactionHash":"0x…"}'`;

export default function DevelopersPage() {
  return <PlatformShell active="developers"><main id="main" className={s.main}><header className={s.docsHeading}><p className={s.eyebrow}>Developer guide</p><h1>Build around<br />clear permissions.</h1><p>One agent per credential. Separate allowances for research data and verification. Testnet infrastructure with explicit execution prerequisites.</p><Link href="/login" className={s.primary}>Create an agent ↗</Link></header><div className={s.docsLayout}><nav className={s.docsNav} aria-label="Developer guide sections"><a href="#quickstart">Quickstart</a><a href="#runs">Run API</a><a href="#marketplace">Marketplace API</a><a href="#runner">Runner setup</a><a href="#authentication">Authentication</a><a href="#errors">Errors and limits</a></nav><div className={s.docsContent}>
    <section id="quickstart"><h2>Start with an agent</h2><p><Link href="/login">Sign in with your wallet</Link>, create an agent in your workspace, and issue an API credential from its credential panel. Copy both the agent ID and the one-time secret. To execute paid work, pair an isolated runner and approve a spending mandate in the agent’s setup panel.</p><p>Set the deployment URL and your agent ID below. Run these commands in Bash or Zsh; <code>read -s</code> accepts your credential without displaying it or putting it in shell history.</p><pre><code>{setup}</code></pre><p>Keep credentials in server-side environment variables. They expire after 30 days and can be revoked immediately from your workspace.</p></section>
    <section id="runs"><h2>Read and request jobs</h2><h3>List your agent’s jobs</h3><pre><code>{list}</code></pre><p>The credential can access only its own agent. An empty job list means no work has been queued.</p><h3>Request a research run</h3><pre><code>{create}</code></pre><div className={s.notice}><strong>A paired runner and signed mandate are required</strong><p>The API queues a persisted job only within your signed scope and available run allowance. Missing or offline execution setup returns an explicit error. No operator wallet or simulation fallback is used.</p></div><p>Send a stable <code>Idempotency-Key</code> for retries of the same request. Use a new key for a new job. Repository identifiers use the <code>owner/repository</code> format.</p><h3>Inspect a specific job</h3><pre><code>{detail}</code></pre><p>Use a real job ID returned by the API. Jobs remain scoped to the credential’s agent.</p></section>
    <section id="marketplace"><h2>Marketplace API</h2><p><Link href="/marketplace">Browse the marketplace</Link> without authentication at <code>GET /api/market/services</code>. Each active listing names its current revision, test-USDC price, Arc recipient, and fixed hosted endpoint. Obolos runs the deterministic repository-metric verifier; sellers choose the price and receive payments directly in their signed-in wallet.</p><h3>Seller endpoints</h3><div className={s.endpointList}><p><code>GET /api/market/services?mine=1</code><span>Owner session · include this wallet’s paused listings</span></p><p><code>POST /api/market/services</code><span>Owner session · JSON name, description, priceAtomic</span></p><p><code>PATCH /api/market/services/:id</code><span>Owner session · publish a new revision or pause the listing</span></p><p><code>GET /api/market/earnings</code><span>Owner session · confirmed orders paid directly to this wallet</span></p></div><p>The API derives the payout address from the authenticated owner; a request cannot supply another recipient.</p><h3>Runner order endpoints</h3><pre><code>{marketOrder}</code></pre><pre><code>{confirmOrder}</code></pre><p>These endpoints accept the private runner Bearer credential, not an agent API key. The order binds the live queued job, selected signed service snapshot, report digest, payer, recipient, amount, and purchased-data transaction before payment. Confirmation independently checks the Arc transfer and returns the hosted verifier’s claim-level checks. Repeating an exact confirmation returns the stored result.</p><div className={s.notice}><strong>Verification is paid execution, not escrow</strong><p>The service checks canonical repository, stars, forks, and open-issues lines plus evidence integrity and freshness. Free-text judgment is outside its certification, and the selected fee is paid even when checks fail.</p></div><p>See the complete <Link href="https://github.com/saiisback/obolos/blob/main/docs/marketplace-setup.md">marketplace and funding guide ↗</Link>.</p></section>
    <section id="runner"><h2>Pair your own runner</h2><p>The web workspace stores accounts, mandates, and jobs. Your runner executes locally against your own loopback broker, keeping wallet and broker credentials outside the platform.</p><ol><li>Use a dedicated checkout and isolated OS user environment for each owner. Separate folders do not isolate shared OS keychains.</li><li>Configure and fund your own testnet broker using the repository’s <code>docs/runner-setup.md</code> guide. Never copy an existing operator’s credentials or payment journal.</li><li>Open your agent, choose <strong>Pair a runner</strong>, and save the one-time runner credential in a private local file with permissions restricted to your OS user. Paste it with an editor; keep it out of shell commands, URLs, and source control.</li><li>Create <code>.env.runner</code> with the exact public pins shown by the workspace and an absolute token-file path.</li></ol><pre><code>{`RUNNER_PLATFORM_URL=https://obolos.app
RUNNER_AGENT_ID=your-agent-id
RUNNER_OWNER_ADDRESS=your-signed-in-wallet-address
RUNNER_TOKEN_FILE=/absolute/private/path/runner-token
RUNNER_DATA_DIR=/absolute/private/path/runner-journal`}</code></pre><p>The runner journal directory must be dedicated to this agent and durable across restarts. Do not delete it to retry an interrupted payment.</p><pre><code>npm run agent:runner</code></pre><p>The command loads your local <code>.env.broker</code> and <code>.env.runner</code>. Your broker must be configured and running. The workspace shows a recent heartbeat as online; a heartbeat does not prove that your wallet is funded or a payment has succeeded.</p><h3>Approve a spending mandate</h3><p>In the agent panel, choose 1–3 repositories, a maximum data price per repository, 1–10 runs, and an expiry of at most 24 hours. Review the exact message and the total HBAR and USDC allowance, then sign with the wallet that owns the workspace.</p><p>This signature authorizes spending within that scope. It is separate from identity sign-in. The runner independently checks the signed owner, agent, origin, providers, limits, and expiry before execution.</p><h3>Queue and reconcile</h3><p>Queue a run in the workspace or through the scoped API. The server reserves a run slot and persists the job before the runner claims it. Active jobs refresh every five seconds while the agent panel is visible.</p><p>A blocked job can indicate a quote above your signed allowance. An uncertain job requires local journal and receipt reconciliation; it is never automatically requeued. Revoking a runner or mandate blocks future authorization but cannot undo work already claimed or settled.</p><p>Reports, source checks, events, and receipts come from the paired runner. Receipts are labeled <strong>Runner-confirmed</strong> until independently checked against the chain. The workspace only links to allowed Hedera and Arc testnet explorers.</p><p>The <Link href="/demo">operator demonstration</Link> remains a separate environment with its own authorization.</p></section>
    <section id="authentication"><h2>Wallet sign-in and API access</h2><p>The browser discovers installed EVM wallets, requests an account, and fetches a sign-in challenge. The wallet signs the exact message with <code>personal_sign</code>.</p><p>The challenge is bound to this deployment’s origin, your address, Arc testnet chain 5042002, and a five-minute nonce. Verification creates a seven-day session in an HttpOnly cookie. Signing out revokes that session.</p><div className={s.endpointList}><p><code>POST /api/auth/challenge</code><span>JSON: <code>{'{"address":"0x…"}'}</code> → sign-in message</span></p><p><code>POST /api/auth/verify</code><span>JSON: <code>{'{"signature":"0x…"}'}</code> → account session</span></p><p><code>GET /api/account</code><span>Account identity and service availability</span></p><p><code>POST /api/auth/logout</code><span>Revoke the current session</span></p></div><p>Account, agent creation, runner pairing, mandate approval, and credential management endpoints use the browser session. API credentials cannot change spending mandates or pair runners. The <code>/api/v1/agents/:id/runs</code> endpoints use a Bearer credential scoped to that agent.</p></section>
    <section id="errors"><h2>Errors and budget units</h2><p>Errors return JSON with <code>error</code> and <code>code</code> fields. Handle non-2xx responses before reading a success payload.</p><pre><code>{'{"error":"Payment execution requires an isolated runner.","code":"RUNNER_REQUIRED"}'}</code></pre><p className={s.caption}>Example error shape; the explanatory message may vary.</p><p>Agent budgets are integers in atomic units: 100,000,000 tinybar = 1 HBAR; 1,000,000 micro-USDC = 1 test USDC. Each per-run budget is capped at one token. A mandate can authorize at most 10 runs, with separate total allowances derived from those per-run limits.</p><p>The workspace converts your decimal input exactly. Integrations should use integer arithmetic and keep HBAR and USDC separate.</p></section>
  </div></div></main></PlatformShell>;
}
