/** Read-only chain reconciliation of one already submitted, exactly signed policy action. */
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {parseAbiItem} from 'viem';
import {economyClient,economyDeployment} from '../src/lib/economy/chain';
import {configuration} from './economy-circle';
import {policyAction} from './economy-policy';
import {savePrivateJson} from './economy-eoa';
import {acquireProcessLock} from './process-lock';
async function main(){const plan=JSON.parse(await readFile(process.argv[2],'utf8')),prepared=policyAction(plan.action),config=configuration(),client=economyClient(),d=economyDeployment()!;const file=join(config.journal,plan.name+'.json');const release=await acquireProcessLock(file+'.lock');try{const op=JSON.parse(await readFile(file,'utf8'));if(!plan.approval?.signature||op.name!==plan.name||op.intent.kind!=='execute')throw Error('Original submitted signed action required');const expectedArgs=['wallet','execute',prepared.signature,...prepared.parameters,plan.observation,plan.approval.deadline,plan.approval.signature,'--contract',d.policy,'--address',config.wallet,'--chain','ARC-TESTNET','--amount','0','--output','json'];if(JSON.stringify(op.intent.args)!==JSON.stringify(expectedArgs))throw Error('Journal differs from signed policy intent');const finalized=await client.getBlock({blockTag:'finalized'});const logs=await client.getLogs({address:d.policy,event:parseAbiItem('event PolicyChanged(uint64 indexed version,bytes32 indexed actionHash,bytes32 indexed observationHash,address actor,bytes32 approvalDigest)'),args:{actionHash:prepared.hash,observationHash:plan.observation},fromBlock:finalized.number-4000n,toBlock:finalized.number});const matches=logs.filter(l=>l.args.actor?.toLowerCase()===config.wallet.toLowerCase()&&l.args.approvalDigest===plan.approval.digest);if(matches.length!==1)throw Error('Expected exactly one finalized event for original approved digest');const log=matches[0],block=await client.getBlock({blockNumber:log.blockNumber});if(block.hash!==log.blockHash)throw Error('Noncanonical policy event');const receipt=await client.getTransactionReceipt({hash:log.transactionHash});if(receipt.status!=='success')throw Error('Policy receipt failed');op.result={...op.result,txHash:log.transactionHash,blockchain:'ARC-TESTNET',sourceAddress:config.wallet,destinationAddress:d.policy,idempotencyKey:op.idempotencyKey,operation:'exact-approved-policy-chain-reconciliation'};op.status='submitted';await savePrivateJson(file,op);console.log(JSON.stringify({name:op.name,transactionHash:log.transactionHash,blockNumber:String(log.blockNumber),reconciledBy:'unique finalized signed approval digest'}));}finally{await release();}}
main().catch(()=>{console.error('Policy reconciliation did not find unique matching final evidence. Original journal preserved.');process.exitCode=1;});
