/** Bounded real-testnet population. Existing journals are never replaced or reset. */
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {BaseError,ContractFunctionRevertedError,createWalletClient,defineChain,encodeFunctionData,http,keccak256,parseAbi,toHex,type Abi,type Address,type Hex} from 'viem';
import {privateKeyToAccount} from 'viem/accounts';
import {economyClient,economyDeployment} from '../src/lib/economy/chain';
import {resourceCategories,type ResourceCategory} from '../src/lib/economy/model';
import {validateServiceDefinition,type ServiceDefinition} from '../src/lib/economy/service-contract';
import {executorInputSchema,runEconomyExecutor,type ExecutorState} from '../src/lib/economy/executor';
import {liveExecutorDependencies} from '../src/lib/economy/executor-live';
import {configuration} from './economy-circle';
import {durableSignedTransaction,loadPrivateJson,savePrivateJson} from './economy-eoa';
import {acquireProcessLock} from './process-lock';
const origin='https://obolos.app',directory=resolve('data/marketplace-exercise-20260912');
const names:Record<ResourceCategory,string>={data:'Atlas — Repository Scout',compute:'Vector — Compute Analyst',inference:'Sage — Research Writer',verification:'Sentinel — Integrity Verifier',storage:'Vault — Artifact Archivist'};
type Member={platformAgentId:string;agentId:Hex;key?:string;definition:ServiceDefinition};
type Roster=Partial<Record<ResourceCategory,Member>>;
async function main(){
 const [mode,categoryArg]=process.argv.slice(2);assert(['inspect','prepare','execute','verify','replay','guards'].includes(mode),'Use inspect, prepare, execute <category>, replay <category>, or verify');
 const identities=JSON.parse(await readFile('data/market-release-v2/state.json','utf8')),owner=privateKeyToAccount(identities.buyerKey),seller=privateKeyToAccount(identities.sellerKey),config=configuration(),d=economyDeployment()!,client=economyClient();
 assert.equal(config.journal,resolve('data/economy-operations'),'Preserve the original Circle/executor journal directory');assert.equal(owner.address.toLowerCase(),'0x1f21897512e5ad2d9aa087a0c8e818a3e2dd22fd');assert.equal(seller.address.toLowerCase(),'0xd2137e6d65165400641aff0e34781d09a0215858');assert.equal(await client.getChainId(),5042002);
 const cookies=new Map<string,string>();async function api(path:string,body?:unknown){const response=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:[...cookies].map(([k,v])=>`${k}=${v}`).join('; ')},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(60000)});for(const raw of response.headers.getSetCookie()){const pair=raw.split(';')[0],i=pair.indexOf('=');cookies.set(pair.slice(0,i),pair.slice(i+1));}const value=await response.json();if(!response.ok)throw Error(`API ${path}: HTTP ${response.status} ${value.code??''}`);return value;}
 const challenge=await api('/api/auth/challenge',{address:owner.address});await api('/api/auth/verify',{signature:await owner.signMessage({message:challenge.message})});
 const rosterFile=join(directory,'roster.json');let roster=await loadPrivateJson<Roster>(rosterFile)??{};
 const policy=(JSON.parse(await readFile('contracts/artifacts/ObolosPolicyEnvelope.json','utf8')) as {abi:Abi}).abi;
 const token='0x3600000000000000000000000000000000000000' as Address,tokenAbi=parseAbi(['function balanceOf(address) view returns(uint256)','function allowance(address,address) view returns(uint256)']);
 if(mode==='inspect'){const agents=await api('/api/agents');console.log(JSON.stringify({agents:agents.agents,ownerGasWei:String(await client.getBalance({address:owner.address})),executorUsdcAtomic:String(await client.readContract({address:token,abi:tokenAbi,functionName:'balanceOf',args:[config.wallet]})),allowanceAtomic:String(await client.readContract({address:token,abi:tokenAbi,functionName:'allowance',args:[config.wallet,d.settlement]})),roster:Object.entries(roster).map(([category,m])=>({category,name:names[category as ResourceCategory],platformAgentId:m!.platformAgentId}))}));return;}
 const release=await acquireProcessLock(join(directory,'exercise.lock'));try{
 if(mode==='prepare'){
  const health=await api('/api/economy/provider/status');assert.equal(health.status,'online');assert(BigInt(await client.getBalance({address:owner.address}))>1000000000000000n,'Owner must already hold testnet gas; no automatic funding');
  const catalog=(await api('/api/economy/services')).services.map(validateServiceDefinition) as ServiceDefinition[],existing=(await api('/api/agents')).agents as {id:string;name:string}[];
  const chain=defineChain({id:5042002,name:'Arc testnet',nativeCurrency:{name:'USDC',symbol:'USDC',decimals:18},rpcUrls:{default:{http:[config.rpc]}}}),wallet=createWalletClient({account:owner,chain,transport:http(config.rpc)});
  async function transact(name:string,data:Hex){return durableSignedTransaction(join(directory,'transactions'),name,{from:owner.address,to:d.policy,data},{sign:async()=>wallet.signTransaction(await wallet.prepareTransactionRequest({account:owner,to:d.policy,data})),receipt:hash=>client.waitForTransactionReceipt({hash,timeout:15000}).catch(()=>null),broadcast:raw=>client.sendRawTransaction({serializedTransaction:raw})});}
  for(const category of resourceCategories){
   const definition=catalog.find(s=>s.category===category&&s.seller===seller.address.toLowerCase()&&s.endpoint===origin+'/api/economy/reference/'+category&&s.unitPriceAtomic==='1000'&&s.quantity==='1');assert(definition,'Exact real provider service required');
   let member=roster[category];if(!member){const matches=existing.filter(a=>a.name===names[category]);assert(matches.length<=1,'Ambiguous existing named agents');const agent=matches[0]??(await api('/api/agents',{name:names[category],description:`Real ${category} specialist in the repository research workflow. Existing owner-operated Circle executor; bounded on-demand jobs, not an independent market participant.`,dataBudgetAtomic:0,verificationBudgetAtomic:2000})).agent;member={platformAgentId:agent.id,agentId:keccak256(toHex(agent.id)),definition};roster[category]=member;await savePrivateJson(rosterFile,roster);}
   const registered=await transact('register-'+category,encodeFunctionData({abi:policy,functionName:'registerAgent',args:[member.agentId,config.wallet,2000n,2000n,86400n]}));
   const allowed=await transact('allow-'+category,encodeFunctionData({abi:policy,functionName:'setCounterparty',args:[member.agentId,resourceCategories.indexOf(category),seller.address,true]}));
   if(!member.key){const issued=await api(`/api/agents/${member.platformAgentId}/keys`,{name:'Bounded marketplace exercise 20260912'});member.key=issued.token;await savePrivateJson(rosterFile,roster);}
   console.log(JSON.stringify({category,name:names[category],platformAgentId:member.platformAgentId,agentId:member.agentId,registrationHash:registered.transactionHash,permissionHash:allowed.transactionHash,totalCapAtomic:'2000'}));
  }
 }else if(mode==='guards'){
  const data=roster.data,compute=roster.compute;assert(data?.key&&compute?.key);const wrongScope=await fetch(origin+`/api/v1/agents/${compute.platformAgentId}/economy/orders`,{headers:{Authorization:`Bearer ${data.key}`}});assert.equal(wrongScope.status,403);const unauthenticated=await fetch(origin+'/api/agents');assert.equal(unauthenticated.status,401);
  const pv=await client.readContract({address:d.policy,abi:policy,functionName:'policyVersion'}),av=await client.readContract({address:d.policy,abi:policy,functionName:'agentVersions',args:[data.agentId]}),orderId=keccak256(toHex('obolos-marketplace-exercise-20260912-rejected'));
  for(const [category,amount,expected] of [[0,3000n,'Limit'],[1,1000n,'Unauthorized']] as const){let rejected=false;try{await client.simulateContract({account:d.settlement,address:d.policy,abi:policy,functionName:'consume',args:[orderId,data.agentId,config.wallet,category,seller.address,amount,pv,av]});}catch(error){const cause=error instanceof BaseError?error.walk(e=>e instanceof ContractFunctionRevertedError):null;rejected=cause instanceof ContractFunctionRevertedError&&cause.data?.errorName===expected;}assert(rejected,expected+' must reject');}
  const consumed=await client.readContract({address:d.policy,abi:policy,functionName:'consumed',args:[orderId]});assert.equal(consumed,false);const result={crossAgentCredentialRejected:true,unauthenticatedAgentsRejected:true,overBudgetRejected:true,wrongCategoryRejected:true,rejectedOrderConsumed:false,paymentSubmitted:false,method:'read-only eth_call against deployed policy'};await savePrivateJson(join(directory,'guards.json'),result);console.log(JSON.stringify(result));
 }else if(mode==='execute'||mode==='replay'){
  assert(resourceCategories.includes(categoryArg as ResourceCategory));const category=categoryArg as ResourceCategory,member=roster[category];assert(member?.key,'Prepare roster first');const inputFile=join(directory,category+'-1.json');let intent=await loadPrivateJson(inputFile);
  async function completed(c:ResourceCategory){const result=await loadPrivateJson<ExecutorState>(join(directory,c+'-completed.json'));assert(result?.phase==='completed','Complete upstream '+c+' first');return result;}
  if(!intent){assert.equal(mode,'execute','Replay requires original saved intent');let input:Record<string,unknown>;if(category==='data')input={repo:'saiisback/obolos'};else if(category==='compute')input={text:JSON.stringify((await completed('data')).output)};else if(category==='inference')input={prompt:'Write a concise factual repository status note using only these fetched GitHub fields. Explain that counts do not prove code quality. Do not invent repository behavior. Data: '+JSON.stringify((await completed('data')).output)+'; integrity computation: '+JSON.stringify((await completed('compute')).output)};else if(category==='verification'){const text=(await completed('inference')).output as {text:string};input={text:text.text,sha256:createHash('sha256').update(text.text).digest('hex')};}else{const report=(await completed('inference')).output as {text:string},verified=(await completed('verification')).output as {passed:boolean};assert.equal(verified.passed,true);input={text:report.text};}
   intent=executorInputSchema.parse({version:1,origin,platformAgentId:member.platformAgentId,orderId:keccak256(toHex('obolos-marketplace-exercise-20260912-'+category+'-1')),owner:owner.address.toLowerCase(),payer:config.wallet.toLowerCase(),definition:member.definition,serviceHash:member.definition.serviceHash,input,maxAmountAtomic:'1000',expiry:String(Math.floor(Date.now()/1000)+86400)});await savePrivateJson(inputFile,intent);
  }
  const parsed=executorInputSchema.parse(intent);const result=await runEconomyExecutor(parsed,join(config.journal,'executor'),liveExecutorDependencies(config,parsed,member.key,{deliveryAttempts:12,pollMs:5000}));await savePrivateJson(join(directory,category+'-completed.json'),result);console.log(JSON.stringify({category,name:names[category],phase:result.phase,orderId:parsed.orderId,paymentHash:result.paymentHash,outputHash:result.outputHash,acknowledgmentHash:result.acknowledgmentHash,output:result.output}));
 }else{
  const results=[];for(const category of resourceCategories){const saved=await loadPrivateJson<ExecutorState>(join(directory,category+'-completed.json'));assert(saved?.phase==='completed');const actual=(await api('/api/economy/orders/'+saved.intent.orderId)).order;assert.equal(actual.state,'fulfilled');assert.equal(actual.outputHash,saved.outputHash);assert.equal(actual.transactionHash,saved.paymentHash);if(category==='storage'){const stored=await api('/api/economy/storage/'+saved.intent.orderId);assert.equal(stored.text,(saved.intent.input as {text:string}).text);}results.push({category,name:names[category],platformAgentId:saved.intent.platformAgentId,orderId:saved.intent.orderId,paymentHash:saved.paymentHash,acknowledgmentHash:saved.acknowledgmentHash,outputHash:saved.outputHash,output:actual.output});}await savePrivateJson(join(directory,'verified.json'),results);console.log(JSON.stringify({verified:results,principalAtomic:'5000',sameOwnerOperated:true}));
 }
 }finally{await release();await api('/api/auth/logout',{}).catch(()=>{});}
}
main().catch(error=>{console.error(error instanceof Error?error.message.split('\n')[0]:'Exercise stopped. Preserve the original journals.');process.exitCode=1;});
