import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {sql} from './db';
import {appOrigin,PlatformError} from './http';
import type {User} from './auth';
import {validateSignedMandate,type SignedMandate} from './execution-contracts';
import {addressSchema,marketReportSchema,type MarketService,type VerificationService,type MarketOrder} from '../market/contracts';
import {reportDigest,verifyMetricReport} from '../market/verifier';
import {verifyMarketTransfer} from '../market/chain';
import type {Report} from '../contracts';
type Row=Record<string,unknown>;
type Runner={id:string;agentId:string};
const editable=z.object({name:z.string().trim().min(1).max(80),description:z.string().trim().max(1000),priceAtomic:z.number().int().min(1000).max(1000000)}).strict();
function service(row:Row):MarketService {return {id:String(row.id),revision:Number(row.revision),name:String(row.name),description:String(row.description),recipient:String(row.recipient),priceAtomic:Number(row.price_atomic),endpoint:`${appOrigin()}/api/market/services/${row.id}`,active:Boolean(row.active),execution:'hosted-metric-verifier',createdAt:new Date(String(row.created_at)).toISOString()};}
export function publicMarketOrder(row:Row):MarketOrder {return {id:String(row.id),jobId:String(row.job_id),serviceId:String(row.service_id),revision:Number(row.revision),payer:String(row.payer),recipient:String(row.recipient),amountAtomic:Number(row.amount_atomic),reportDigest:String(row.report_digest),createdAt:new Date(String(row.created_at)).toISOString(),expiresAt:new Date(String(row.expires_at)).toISOString(),status:row.status as MarketOrder['status'],...(row.transaction_hash?{transactionHash:String(row.transaction_hash),result:row.result as MarketOrder['result'],chainConfirmed:true}:{})};}
export async function listMarketServices(userId?:string) {const db=sql();const rows=userId?await db`SELECT * FROM platform_market_services WHERE user_id=${userId} ORDER BY created_at DESC LIMIT 100`:await db`SELECT * FROM platform_market_services WHERE active=true ORDER BY created_at DESC LIMIT 100`;return rows.map(service);}
export async function getVerificationService(id:string):Promise<VerificationService> {z.uuid().parse(id);const rows=await sql()`SELECT * FROM platform_market_services WHERE id=${id} AND active=true`;if(!rows[0])throw new PlatformError(404,'SERVICE_NOT_FOUND','This verification service is unavailable.');const {description,active,execution,createdAt,...snapshot}=service(rows[0]);void description;void active;void execution;void createdAt;return snapshot;}
export async function createMarketService(user:User,input:unknown) {const v=editable.parse(input);const rows=await sql()`INSERT INTO platform_market_services(id,user_id,name,description,recipient,price_atomic) VALUES(${randomUUID()},${user.id},${v.name},${v.description},${user.address.toLowerCase()},${v.priceAtomic}) RETURNING *`;return service(rows[0]);}
export async function updateMarketService(user:User,id:string,input:unknown) {z.uuid().parse(id);const v=editable.partial().extend({active:z.boolean().optional()}).strict().refine(v=>Object.keys(v).length>0).parse(input);const rows=await sql()`UPDATE platform_market_services SET name=COALESCE(${v.name??null},name),description=COALESCE(${v.description??null},description),price_atomic=COALESCE(${v.priceAtomic??null},price_atomic),active=COALESCE(${v.active??null},active),revision=revision+1 WHERE id=${id} AND user_id=${user.id} RETURNING *`;if(!rows[0])throw new PlatformError(404,'SERVICE_NOT_FOUND','Service not found.');return service(rows[0]);}
export async function marketEarnings(userId:string) {const db=sql();const [rows,total]=await Promise.all([db`SELECT o.* FROM platform_market_orders o JOIN platform_market_services s ON s.id=o.service_id WHERE s.user_id=${userId} AND o.status='fulfilled' ORDER BY o.created_at DESC LIMIT 100`,db`SELECT COALESCE(SUM(o.amount_atomic),0)::text AS total FROM platform_market_orders o JOIN platform_market_services s ON s.id=o.service_id WHERE s.user_id=${userId} AND o.status='fulfilled'`]);return {orders:rows.map(publicMarketOrder),totalAtomic:String(total[0].total)};}
export async function getMarketOrder(id:string,scope:{runner?:Runner;userId?:string}) {z.uuid().parse(id);const db=sql();const rows=scope.runner?await db`SELECT o.* FROM platform_market_orders o JOIN platform_jobs j ON j.id=o.job_id WHERE o.id=${id} AND o.runner_id=${scope.runner.id} AND j.agent_id=${scope.runner.agentId} AND EXISTS(SELECT 1 FROM platform_runners WHERE id=${scope.runner.id} AND revoked_at IS NULL)`:await db`SELECT o.* FROM platform_market_orders o JOIN platform_jobs j ON j.id=o.job_id JOIN platform_agents a ON a.id=j.agent_id WHERE o.id=${id} AND a.user_id=${scope.userId??''}`;if(!rows[0])throw new PlatformError(404,'ORDER_NOT_FOUND','Order not found.');return rows[0];}
export async function createMarketOrder(runner:Runner,body:unknown) {
 const input=z.object({jobId:z.uuid(),payer:addressSchema,dataTransactionId:z.string().regex(/^0\.0\.\d+@\d+\.\d+$/),report:marketReportSchema}).strict().parse(body),db=sql(),digest=reportDigest(input.report);
 const old=await db`SELECT * FROM platform_market_orders WHERE job_id=${input.jobId} AND runner_id=${runner.id}`;
 if(old[0]){await getMarketOrder(String(old[0].id),{runner});if(old[0].report_digest!==digest||old[0].payer!==input.payer.toLowerCase()||old[0].data_transaction_id!==input.dataTransactionId)throw new PlatformError(409,'ORDER_CONFLICT','This job already has an order for a different report or payer.');return publicMarketOrder(old[0]);}
 const rows=await db`SELECT j.repos,m.fields,m.message,m.signature,u.address FROM platform_jobs j JOIN platform_mandates m ON m.id=j.mandate_id JOIN platform_agents a ON a.id=j.agent_id JOIN platform_users u ON u.id=a.user_id WHERE j.id=${input.jobId} AND j.agent_id=${runner.agentId} AND j.runner_id=${runner.id} AND j.status='running' AND m.approved_at IS NOT NULL AND m.revoked_at IS NULL AND m.expires_at>now() AND EXISTS(SELECT 1 FROM platform_runners WHERE id=${runner.id} AND revoked_at IS NULL)`;
 const job=rows[0];if(!job)throw new PlatformError(409,'JOB_UNAVAILABLE','An assigned running job with an active signed mandate is required.');
 const mandate={...(job.fields as SignedMandate),message:job.message,signature:job.signature} as SignedMandate;
 if(!await validateSignedMandate(mandate,{owner:String(job.address),agentId:runner.agentId,origin:appOrigin()})||!mandate.verificationService)throw new PlatformError(409,'MANDATE_REQUIRED','An active signed marketplace mandate is required.');
 const selected=await getVerificationService(mandate.verificationService.id);
 if(JSON.stringify(selected)!==JSON.stringify(mandate.verificationService)&&Object.keys(selected).some(k=>selected[k as keyof VerificationService]!==mandate.verificationService![k as keyof VerificationService]))throw new PlatformError(409,'SERVICE_CHANGED','Service changed; sign a new mandate before buying.');
 if(selected.priceAtomic>mandate.verificationBudgetAtomic||JSON.stringify(input.report.evidence.map(e=>e.repo))!==JSON.stringify(job.repos))throw new PlatformError(400,'INVALID_REPORT','Report scope or service price exceeds the signed job.');
 const purchased=await db`SELECT * FROM platform_service_payments WHERE state='settled' AND (transaction_id=${input.dataTransactionId} OR settlement->>'transaction'=${input.dataTransactionId})`;
 const paid=purchased[0];
 if(purchased.length!==1||!paid.evidence||!mandate.allowedProviders.includes(String(paid.provider_id))||JSON.stringify(paid.repos)!==JSON.stringify(job.repos)||reportDigest({...input.report,evidence:paid.evidence as Report['evidence']})!==digest||Number(paid.amount_atomic)>mandate.dataBudgetAtomic||Number(paid.amount_atomic)>mandate.maxDataUnitPriceAtomic*input.report.evidence.length)throw new PlatformError(409,'PAID_EVIDENCE_REQUIRED','This report must match an existing settled evidence purchase within its signed scope.');
 const expiresAt=new Date(Math.min(Date.now()+15*60000,Date.parse(mandate.expiresAt))).toISOString();
 let inserted:Row[];
 try {inserted=await db`INSERT INTO platform_market_orders(id,job_id,service_id,revision,runner_id,payer,recipient,amount_atomic,report_digest,report,service_snapshot,expires_at,data_transaction_id,data_source_id)
 SELECT ${randomUUID()},j.id,s.id,s.revision,${runner.id},${input.payer.toLowerCase()},s.recipient,s.price_atomic,${digest},${JSON.stringify(input.report)}::jsonb,${JSON.stringify(selected)}::jsonb,${expiresAt},${input.dataTransactionId},${String(paid.transaction_id)} FROM platform_jobs j JOIN platform_mandates m ON m.id=j.mandate_id JOIN platform_market_services s ON s.id=${selected.id} WHERE j.id=${input.jobId} AND j.runner_id=${runner.id} AND j.status='running' AND m.revoked_at IS NULL AND m.expires_at>now() AND s.active=true AND s.revision=${selected.revision} AND EXISTS(SELECT 1 FROM platform_runners WHERE id=${runner.id} AND revoked_at IS NULL) ON CONFLICT(job_id) DO NOTHING RETURNING *`;}catch(error){if((error as {code?:string}).code==='23505')throw new PlatformError(409,'EVIDENCE_REUSED','This evidence purchase already belongs to another verification order.');throw error;}
 if(!inserted[0]){const replay=await db`SELECT * FROM platform_market_orders WHERE job_id=${input.jobId} AND runner_id=${runner.id}`;if(replay[0]&&replay[0].report_digest===digest&&replay[0].payer===input.payer.toLowerCase()&&replay[0].data_transaction_id===input.dataTransactionId)return publicMarketOrder(replay[0]);throw new PlatformError(409,'ORDER_CONFLICT','The order or service changed.');}
 return publicMarketOrder(inserted[0]);
}
export async function confirmMarketOrder(runner:Runner,id:string,body:unknown) {
 const {transactionHash}=z.object({transactionHash:z.string().regex(/^0x[0-9a-fA-F]{64}$/).transform(v=>v.toLowerCase())}).strict().parse(body);
 const row=await getMarketOrder(id,{runner});
 if(row.status==='fulfilled'){if(row.transaction_hash!==transactionHash)throw new PlatformError(409,'ORDER_CONFLICT','Order already fulfilled by a different transaction.');return publicMarketOrder(row);}
 const order=publicMarketOrder(row),proof=await verifyMarketTransfer(transactionHash as `0x${string}`,order),result=verifyMetricReport(row.report as Report,new Date(Number(proof.timestamp)*1000)),db=sql();
 try {
 const rows=await db`UPDATE platform_market_orders SET transaction_hash=${transactionHash},proof=${JSON.stringify(proof)}::jsonb,result=${JSON.stringify(result)}::jsonb,status='fulfilled' WHERE id=${id} AND status='quoted' AND EXISTS(SELECT 1 FROM platform_runners WHERE id=${runner.id} AND revoked_at IS NULL) RETURNING *`;
 if(rows[0])return publicMarketOrder(rows[0]);
 }catch(error){if((error as {code?:string}).code==='23505')throw new PlatformError(409,'PAYMENT_REUSED','This transaction already belongs to another order.');throw error;}
 const replay=await getMarketOrder(id,{runner});if(replay.transaction_hash===transactionHash)return publicMarketOrder(replay);throw new PlatformError(409,'ORDER_CONFLICT','Order changed while confirming payment.');
}
